In [70]:
## Numeric int, float

In [1]:
a=1
type(a)


int

In [2]:
b= 2.8
type(2.8)

float

In [3]:
## Sequence list, tuple

In [4]:
type([4, 6, 7])

list

In [5]:
type((105, 110))

tuple

In [6]:
## String str

In [7]:
type("I like Math!")


str

In [8]:
## Mapping dict

In [9]:
type({"number of student": 8, "p": 5})

dict

In [10]:
##set

In [11]:
type({"number of student", "p"})

set

In [12]:
##Boolean 

In [13]:
1 == 2

False

In [14]:
c=("I like Math!")

In [15]:
print(c[2])

l


Excercise1: Assign a list to a variable and check the type and print an element using index!

Excercise2: Assign a flot to a variable and use the print() function to print out the following sentence "the type of 2.8 is <class 'float'>"

In [16]:
##Arithmetic operators

In [17]:
1+5*4

21

In [18]:
(1+5)*4

24

In [19]:
30%10

0

In [20]:
15//2

7

In [21]:
4**3

64

In [22]:
##Conditional Statements 

In [23]:
grade=60

if grade>50:
    print("you pass the test")

you pass the test


In [24]:
a=34
if a<20:
    print("you are a winner")
else:
    print("you are a loser")
    

you are a loser


In [25]:
grade=60

if grade>50:
print("you pass the test")

IndentationError: expected an indented block after 'if' statement on line 3 (1729346631.py, line 4)

Excercise3: Given two numbers a and b, write a Python code to check if a is divisible by b

In [26]:
## for and while loop

In [27]:
animals = ["dog", "cat", "bird"]
for x in animals:
    print(x)

dog
cat
bird


In [28]:
animals = ["dog", "cat", "bird"]
for x in animals:
    print(x)
    if x == "cat":
        break

dog
cat


In [29]:
x = range(10, 20)
for n in x:
    print(n)

10
11
12
13
14
15
16
17
18
19


In [30]:
x = range(10, 20,2)
for n in x:
    print(n)

10
12
14
16
18


Exercise4: What numbers between 2 and 30 are even and odd?

In [31]:
i = 1
while i < 11:
    print(i)
    i += 1

1
2
3
4
5
6
7
8
9
10


Exercise5:print out the numbers from 100 to 0 in steps of 10, using while loop



In [32]:
## Def function

In [33]:
def add_numbers(num1, num2):
    sum = num1 + num2
    return sum
print(add_numbers(3, 5))

8


Exercise6:What is the area of a rectangle with a length of 2 and a width of 4? (use def function)

In [34]:
## Python Arrays

In [35]:
array_ex = [1, 2, 3, 4, 5]
print(array_ex)

[1, 2, 3, 4, 5]


In [36]:
x = array_ex[0]
print(x)

1


In [37]:
x = len(array_ex)
print(x)

5


In [38]:
array_ex.append(5)
print(array_ex)

[1, 2, 3, 4, 5, 5]


In [39]:
array_ex.pop(1)
print(array_ex)

[1, 3, 4, 5, 5]


Exercise7:Write a Python program to find the largest number in a given array of numbers

In [3]:
import numpy as np

In [4]:
x = np.array([5, 4, -7, 11])
print(x)

[ 5  4 -7 11]


In [5]:
y = np.array([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)

[[4 5 0]
 [3 7 9]
 [2 1 2]]


In [6]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [7]:
b = np.arange(10).reshape(2, 5) 
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
type(b)

numpy.ndarray

In [9]:
b.ndim

2

In [10]:
b.size

10

In [11]:
b.dtype

dtype('int64')

In [12]:
b = b.astype(np.float64)
print(b)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


Exercise8:Create a 3-dimensional array using np.arange() and reshape

Exercise9:Create an array of dictionaries and print it

In [13]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


Exercise10:Extract the value 15 from the z array above by indexing

In [14]:
##array slice

In [15]:
z[1, 2, :]

array([16, 17, 18])

In [22]:
y[:2, :]


array([[4, 5, 0],
       [3, 7, 9]])

In [23]:
y[1:, :]

array([[3, 7, 9],
       [2, 1, 2]])

Exercise11:Extract the first and 2rd rows and all columns from the z array above by indexing