In [2]:
import numpy as np

In [3]:
x = np.array([5, 4, -7, 11])
print(x)


[ 5  4 -7 11]


In [4]:
y = np.array([[4, 5, 0], [3, 7, 9], [2, 1, 2]])
print(y)

[[4 5 0]
 [3 7 9]
 [2 1 2]]


In [5]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [6]:
b = np.arange(10).reshape(2, 5) 
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
type(b)

numpy.ndarray

In [8]:
b.shape

(2, 5)

In [9]:
b.size

10

In [10]:
b.ndim

2

Exercise1:Create a 3-dimensional array using np.arange() and reshape and check for shape, size, dimension

In [11]:
z = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


Exercise2:Extract the value 15 from the z array above by indexing

In [12]:
##array slice

In [13]:
z[1, 2, :]

array([16, 17, 18])

In [14]:
y[:2, :]

array([[4, 5, 0],
       [3, 7, 9]])

In [15]:
y[1:, :]

array([[3, 7, 9],
       [2, 1, 2]])

Exercise3:Extract the 2nd layer, first and 2nd rows and all columns from the z array above by slice and indexing

In [16]:
##vectorizing and summarizing

In [17]:
x+2

array([ 7,  6, -5, 13])

In [18]:
x-1

array([ 4,  3, -8, 10])

In [19]:
x**2

array([ 25,  16,  49, 121])

In [20]:
np.abs(x)

array([ 5,  4,  7, 11])

In [21]:
np.max(x)

11

In [22]:
np.median(x)

4.5

Exercise4: Write a Python program to find the median of a given array of numbers with for and if loop

Exercise5: Write a Python program to find the median of a given array of numbers using vectorizing

In [23]:
x<5 

array([False,  True,  True, False])

In [24]:
x==11

array([False, False, False,  True])

In [25]:
~(x > 1)

array([False, False,  True, False])

In [26]:
##masks for subsetting

In [27]:
x[x < 5]

array([ 4, -7])

In [28]:
x[x < 5]=40
x


array([ 5, 40, 40, 11])

Exercise6: Substitute the values from array x which are not greater than 20,or equal to 11 with 30 (use logical operator not and or)

In [29]:
np.sum(x)

96

In [30]:
np.sum(x<35)

2

In [31]:
np.sum(y, axis=0)

array([ 9, 13, 11])

In [32]:
np.sum(y, axis=1)

array([ 9, 19,  5])

Reference: https://jupyter.org
https://the-turing-way.netlify.app/communication/binder/zero-to-binder.html
https://docs.python.org
https://geobgu.xyz/py/
